### PR TITLE
Switch from "beta_set_page_config" to "set_page_config"

### PR DESCRIPTION
**Pull request by carolinedlu**
Using "beta_set_page_config" results in an error; error is resolved by switching to "set_page_config"

### CODE REVIEW

**Review by gmerticariu — APPROVED** [review]

**Comment by astayleraz** [comment]
Screen Shot 2021-05-13 at 3 22 34 PM
This is causing this error now. Can you please revert this commit? Thanks

**Comment by carolinedlu** [comment]
> Screen Shot 2021-05-13 at 3 22 34 PM
> This is causing this error now. Can you please revert this commit? Thanks

Hi @astayleraz, what version of Streamlit are you using?

**Comment by vdonato** [comment]
Whoops, sorry about that @astayleraz!

The error occurs because we didn't realize that the version the app is pinned to in `requirements.txt` didn't have `st.set_page_config` out of beta yet.

I have a fix out in #8 that should fix things once it's merged.

**Comment by astayleraz** [comment]
Awesome. Thank you!

**Pull request merged**
