### PR TITLE
Replace st.experimental_get_query_params() with st.query_params

### PR DESCRIPTION
**Pull request by sowmyamanojna**
Replace st.experimental_get_query_params() with st.query_params.

### CODE REVIEW

**Review by sfc-gh-zblackwood — APPROVED** [review]

**Comment by sowmyamanojna** [comment]
Made an additional change to query_params for the case when the slider is moved.

**Comment by davidaparicio** [comment]
Is @streamlit/eng @monchier can perform the review and the merge?

**Comment by davidaparicio** [comment]
@sowmyamanojna can you fix `pickup_hour = int(st.query_params["pickup_hour"][0])` by pickup_hour = int(st.query_params["pickup_hour"])

You can try in your implementation with http://<streamlit_URL:8501>/?pickup_hour=21 will select 2 instead 21 ;-)

**Comment by kmcgrady** [comment]
Closing this cause I have made changes to use the new query params that works properly.

**Pull request closed without merging**
